### ISSUE TITLE
Meanings while training

### ISSUE THREAD

**Issue by SlimRG** [XPixelGroup/BasicSR#144]
I wonder what means 

> l_g_pix: 1.4306e-04 l_g_fea: 3.1057e-01 l_g_gan: 3.4863e-02 l_d_real: 1.6664e-03 l_d_fake: 1.3277e-03 D_real: -1.4680e+01 D_fake: -2.1651e+01

**Comment by xinntao** [comment]
They are the training outputs, such as losses and model outputs.

**Comment by SlimRG** [comment]
I know this, I'm not stupid!
I want to know - what losses and model outputs are they?

**Comment by xinntao** [comment]
l_g_pix: pixel loss (usually L1 or MSE loss) of the generator
l_g_fea: feature loss (perceptual loss, usually with VGG network) of the generator
l_g_gan: adversarial loss (GAN loss) of the generator
l_d_real: adversarial loss of the discriminator when input is the real data (GT)
l_d_fake: adversarial loss of the discriminator when input is the fake data (the outputs of the generator) D_real: the outputs of the discriminator when input is the real dada
D_fake: the outputs of the discriminator when input is the fake data

**Comment by young666** [comment]
> I know this, I'm not stupid!
> I want to know - what losses and model outputs are they?

Did you really read the code + paper before asking? In ./models/SRRaGAN_model.py have all the things you need, have you ever tried looking at it for once?

**Comment by XiaotianM** [comment]
> l_g_pix: pixel loss (usually L1 or MSE loss) of the generator
> l_g_fea: feature loss (perceptual loss, usually with VGG network) of the generator
> l_g_gan: adversarial loss (GAN loss) of the generator
> l_d_real: adversarial loss of the discriminator when input is the real data (GT)
> l_d_fake: adversarial loss of the discriminator when input is the fake data (the outputs of the generator) D_real: the outputs of the discriminator when input is the real dada
> D_fake: the outputs of the discriminator when input is the fake data

Hi, xintao.  Would you like to tell me how to discriminate the convergence of ESRGAN? The G Network is seems ok when D(G(x)) > D(real) ?  In other words,  a simple condition for judging convergence  is the value of D_fake is closed D_real ?  Is that true?

**Comment by young666** [comment]
> > l_g_pix: pixel loss (usually L1 or MSE loss) of the generator
> > l_g_fea: feature loss (perceptual loss, usually with VGG network) of the generator
> > l_g_gan: adversarial loss (GAN loss) of the generator
> > l_d_real: adversarial loss of the discriminator when input is the real data (GT)
> > l_d_fake: adversarial loss of the discriminator when input is the fake data (the outputs of the generator) D_real: the outputs of the discriminator when input is the real dada
> > D_fake: the outputs of the discriminator when input is the fake data
> 
> Hi, xintao. Would you like to tell me how to discriminate the convergence of ESRGAN? The G Network is seems ok when D(G(x)) > D(real) ? In other words, a simple condition for judging convergence is the value of D_fake is closed D_real ? Is that true?

I think yes. And another more visual way to know this is when the loss does not fluctuate anymore
