### ISSUE TITLE
[DFDNET] Cannot import fused_act and upfirdn2d.

### ISSUE THREAD

**Issue by niizam** [XPixelGroup/BasicSR#363]
I'm running this cell in [colab](https://colab.research.google.com/drive/1RoNDeipp9yPjI3EbpEbUhn66k5Uzg4n8?usp=sharing#scrollTo=iOOKuMG_VHg3)
`!python inference/inference_dfdnet.py --upscale_factor 1 --test_path datasets/childhood/ --official_adaption True`
and got error like this

> Cannot import fused_act and upfirdn2d. Ignore this warning if they are not used. Otherwise install BasicSR with compiling them.
Cannot import dcn. Ignore this warning if dcn is not used. Otherwise install BasicSR with compiling dcn.
Traceback (most recent call last):
  File "inference/inference_dfdnet.py", line 116, in <module>
    net = DFDNet(64, dict_path=args.dict_path).to(device)
  File "/content/BasicSR/basicsr/models/archs/dfdnet_arch.py", line 73, in __init__
    self.dict = torch.load(dict_path)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by xinntao** [comment]
I have not encountered this problem. 

You may try to download the dict and run it again.

**Comment by algeronwaterschoot** [comment]
`scripts/download_pretrained_models.py DFDNet` links to a resource hosted on Google Drive, which is subject to a daily download quota.

> Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

Try this [alternative link](https://drive.google.com/drive/folders/1bayYIUMCSGmoFPyd4Uu2Uwn347RW-vl5).
