### ISSUE TITLE
Cannot train BasicVSR

### ISSUE THREAD

**Issue by Sadat75** [XPixelGroup/BasicSR#516]
I have downloaded the pre-trained model of spynet: (spynet_sintel_final-3d2a1287.pth). But it shows the error given below.

RuntimeError: Error(s) in loading state_dict for SpyNet:
	Missing key(s) in state_dict: "basic_module.0.basic_module.0.conv.weight", "basic_module.0.basic_module.0.conv.bias", "basic_module.0.basic_module.1.conv.weight", "basic_module.0.basic_module.1.conv.bias", "basic_module.0.basic_module.2.conv.weight", "basic_module.0.basic_module.2.conv.bias", "basic_module.0.basic_module.3.conv.weight", "basic_module.0.basic_module.3.conv.bias", "basic_module.0.basic_module.4.conv.weight", "basic_module.0.basic_module.4.conv.bias", "basic_module.1.basic_module.0.conv.weight", "basic_module.1.basic_module.0.conv.bias", "basic_module.1.basic_module.1.conv.weight", "basic_module.1.basic_module.1.conv.bias", "basic_module.1.basic_module.2.conv.weight", "basic_module.1.basic_module.2.conv.bias", "basic_module.1.basic_module.3.conv.weight", "basic_module.1.basic_module.3.conv.bias", "basic_module.1.basic_module.4.conv.weight", "basic_module.1.basic_module.4.conv.bias", "basic_module.2.basic_module.0.conv.weight", "basic_module.2.basic_module.0.conv.bias", "basic_module.2.basic_module.1.conv.weight", "basic_module.2.basic_module.1.conv.bias", "basic_module.2.basic_module.2.conv.weight", "basic_module.2.basic_module.2.conv.bias", "basic_module.2.basic_module.3.conv.weight", "basic_module.2.basic_module.3.conv.bias", "basic_module.2.basic_module.4.conv.weight", "basic_module.2.basic_module.4.conv.bias", "basic_module.3.basic_module.0.conv.weight", "basic_module.3.basic_module.0.conv.bias", "basic_module.3.basic_module.1.conv.weight", "basic_module.3.basic_module.1.conv.bias", "basic_module.3.basic_module.2.conv.weight", "basic_module.3.basic_module.2.conv.bias", "basic_module.3.basic_module.3.conv.weight", "basic_module.3.basic_module.3.conv.bias", "basic_module.3.basic_module.4.conv.weight", "basic_module.3.basic_module.4.conv.bias", "basic_module.4.basic_module.0.conv.weight", "basic_module.4.basic_module.0.conv.bias", "basic_module.4.basic_module.1.conv.weight", "basic_module.4.basic_module.1.conv.bias", "basic_module.4.basic_module.2.conv.weight", "basic_module.4.basic_module.2.conv.bias", "basic_module.4.basic_module.3.conv.weight", "basic_module.4.basic_module.3.conv.bias", "basic_module.4.basic_module.4.conv.weight", "basic_module.4.basic_module.4.conv.bias", "basic_module.5.basic_module.0.conv.weight", "basic_module.5.basic_module.0.conv.bias", "basic_module.5.basic_module.1.conv.weight", "basic_module.5.basic_module.1.conv.bias", "basic_module.5.basic_module.2.conv.weight", "basic_module.5.basic_module.2.conv.bias", "basic_module.5.basic_module.3.conv.weight", "basic_module.5.basic_module.3.conv.bias", "basic_module.5.basic_module.4.conv.weight", "basic_module.5.basic_module.4.conv.bias". 
	Unexpected key(s) in state_dict: "params".

**Comment by LiangbinXie** [comment]
This error is strange.  I download the pre-trained model of spynet from https://drive.google.com/file/d/1VZz1cikwTRVX7zXoD247DB7n5Tj_LQpF/view?usp=sharing. Then I train the BasicVSR (I set the debug mode for convenience), here is the specific yaml file and the output:
![image](https://user-images.githubusercontent.com/52127135/162114525-4c66a649-0b6e-4578-b193-b39d046150e2.png)

![image](https://user-images.githubusercontent.com/52127135/162114550-36c921b4-dcea-4c73-9e0b-f7e55d2e82ad.png)

I do not encounter the problem you mentioned.  You can re-download the pre-trained  spynet model from https://drive.google.com/file/d/1VZz1cikwTRVX7zXoD247DB7n5Tj_LQpF/view?usp=sharing and try the latest version of BasicSR~

**Comment by YiRuChenbilibili** [comment]
I have the same problem. How did you fix it?

**Comment by xinntao** [comment]
@YiRuChenbilibili @Sadat75 
We have tested the latest version and do not encounter this problem. 

You may need to update to the latest version and have a try.

If you still have this issue, please re-open this issue or open a new issue. Thanks 😄
