### ISSUE TITLE
The question about training for SwinIR

### ISSUE THREAD

**Issue by cocoxw** [XPixelGroup/BasicSR#518]
Thanks for your sharing and contribution! I meet some problems recently. When I am training SwinIR in BasicSR,  it will automatically terminate the training in the middle. But this problem did not occur when I trained other models. I try to solve but no success, could you give me some advice?
![8fcc366de0fd37480d55d54aa6f6c5a](https://user-images.githubusercontent.com/59959139/163668383-fd5b12b3-a3bf-4883-bf7e-b60ef68302f6.jpg)

**Comment by BITchenxiaozhen** [comment]
Have you solve it? I meet the same problem with you.

**Comment by cocoxw** [comment]
> Have you solve it? I meet the same problem with you.

I didn't solve the problem completely. However, I find that the training for SwinIR will always stop at exactly half of the total iters. If you want train 500,000 iters, you can set 1,000,000 iters for training. 
e.g.:
scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 1000000
  warmup_iter: -1  # no warm up
