### ISSUE TITLE
百度和谷歌云盘中找不到 edvr_reds_pretrained_new.pth 预训练模型

### ISSUE THREAD

**Issue by yiyuqi0301** [XPixelGroup/BasicSR#536]
在 train_IconVSR_REDS.yml 中 edvr_path 使用的是 edvr_reds_pretrained_new.pth

![Snipaste_2022-06-01_13-18-19](https://user-images.githubusercontent.com/41294817/171334188-da044b2c-6e08-4267-b7de-31d2109935b1.png)

但是在百度和谷歌网盘中找不到这个预训练模型

**Comment by LiangbinXie** [comment]
Some models are renamed in the new version. For 'edvr_reds_pretrained_new.pth', the new name is 'EDVR_REDS_pretrained_for_IconVSR-f62a2f1e.pth'. The corresponding download link is https://drive.google.com/drive/folders/1FM36uk2OT01_ZgsF1LUfN4GPzRaS0N1l
