### ISSUE TITLE
1.4.0 broke importing basicsr.losses.gan_loss

### ISSUE THREAD

**Issue by apolinario** [XPixelGroup/BasicSR#546]
GFPGAN, REALERSEGAN and other models (including the official example here: https://github.com/XPixelGroup/BasicSR/blob/master/basicsr/models/stylegan2_model.py) use code such as `from basicsr.losses.gan_loss import r1_penalty`

But on 1.4.0 running this line will throw an error - breaking backwards compatibility: 

```
 File "/content/GFPGAN/gfpgan/models/gfpgan_model.py", line 6, in <module>
    from basicsr.losses.gan_loss import r1_penalty
ModuleNotFoundError: No module named 'basicsr.losses.gan_loss'
```

**Comment by apolinario** [comment]
Error on my end

**Comment by djdookie** [comment]
How did you solve this?

**Comment by xinntao** [comment]
This error is due to the updated version of BasicSR

Please update the BasicSR version to the latest, which will address this issue.

If you still have the issue, please re-open it.
