### ISSUE TITLE
ESRGAN - Training setting

### ISSUE THREAD

**Issue by cheeku18** [XPixelGroup/BasicSR#549]
In the config file to train ESRGAN, we have total_iters and n_d_iters. Could someone explain the difference between those?

**Comment by xinntao** [comment]
total_iters： total training iterations.
net_d_iters: train `net_d_iters` iterations for the discriminator and then train one iteration for the generation. 

You can refer to the codes for more details.

**Comment by cheeku18** [comment]
As per the code in https://github.com/XPixelGroup/BasicSR/blob/db589b485b6ac5a1cfc47c0961dcf52ba1fb369a/basicsr/models/esrgan_model.py#L22, lines from 23 to 48 has the code for optimizing the generator -  am I correct? Lines 51 - 83 optimizes the discriminator which happens at each iteration, right?

Example 1:
total_iters = 1000
net_d_iters = 2 
self.net_d_init_iters =0

check on line 22 ---- 
if (current_iter % self.net_d_iters == 0 and current_iter > self.net_d_init_iters):
iteration 1: 
(i.e) 1 % 2 !=0 
generator optimization is skipped.
discriminator is optimized

iteration 2: 
(i.e) 2 % 2 ==0 
generator is optimization.
discriminator is optimized

this pattern continues. Looking at the flow of code, it looks like the discriminator is optimized at each iteration and the generator is optimized every net_d_iters. Is my understanding right? Am I missing some thing here?
