### ISSUE TITLE
The confusion about learning rate

### ISSUE THREAD

**Issue by qwerdf4** [XPixelGroup/BasicSR#551]
In the ESRGAN it is written‘’The learning rate is initialized as 2x10^-4 and decayed by a factor of 2 every 2 x 10^5 of mini-batch updates‘’，but the learning rate at 2 x 10^5 iterations is 1x10^-7, the decayed factor is not 2, How should I understand

**Comment by xinntao** [comment]
For the PSNR model, we update the learning rate scheduler with  `type: CosineAnnealingRestartLR`, which differs from our paper. Such an update results in a better PSNR result.

But for the GAN model, we still use the `type: MultiStepLR` learning rate scheduler.
