### ISSUE TITLE
是否是一个bug？

### ISSUE THREAD

**Issue by cslvjt** [XPixelGroup/BasicSR#601]
https://github.com/XPixelGroup/BasicSR/blob/033cd6896d898fdd3dcda32e3102a792efa1b8f4/basicsr/models/sr_model.py#LL165C41-L165C41

当模型不使用net_g_ema时，这句话报错

**Comment by wwhio** [comment]
是的，您可以试着修复它。
并鼓励您参与到 BasicSR 的建设，给 BasicSR 提交一个 PR。

参考代码：
https://github.com/XPixelGroup/BasicSR/blob/033cd6896d898fdd3dcda32e3102a792efa1b8f4/basicsr/models/sr_model.py#L122-L130
