### ISSUE TITLE
【BUG】模型提前终止训练，进入latest model的推理

### ISSUE THREAD

**Issue by 11923303233** [XPixelGroup/BasicSR#639]
我使用844张图片生成lmdb训练，设置50W iter，但是在490600时保存latest model模型，进入最后的验证阶段。

**Comment by guoxiangyv** [comment]
你好，我也遇到了和你相同的问题，训练提前终止，请问你找到原因了吗。

**Comment by JianHaoYin** [comment]
同问，不知道为什么训练提前终止

**Comment by Bruce-WangGF** [comment]
> 我使用844张图片生成lmdb训练，设置50W iter，但是在490600时保存latest model模型，进入最后的验证阶段。

它的停止逻辑有两个，iter和epoch，有一个达到阈值就会停止，可以将dataset_enlarge_ratio设置得大一点
